### ISSUE TITLE
Cannot run in docker container based on alpine (musl libc)

### ISSUE THREAD

**Issue by srbetasign** [Kocal/BiomeJsBundle#15]
Hello,

i'm working with a docker image based on [alpine](https://hub.docker.com/_/alpine) and i have tried to use BiomejsBundle.

But when i run the command, the following error occurs:
```shell
$ php bin/console biomejs:check .

 ! [NOTE] Executing Biome.js "check" (pass -v to see more details).                                                     

sh: exec: line 0: /usr/local/src/app/var/biomejs/v1.8.3/biome-linux-x64: not found
                                                                                                                        
 [ERROR] Biome.js check failed: see output above.            
```
I have tried many versions of the bin biome-linux-x64 and the same error occurs.

This is because Alpine use the musl version of the libc which seems to be not compatible with the bin biome-linux-x64 (build with the standard libc).

So would it be possible to build this bin with the musl version of the libc ?

Thank you in advance for your reply.

And thank you for this bundle ! :)

**Comment by srbetasign** [comment]
Hello again,
 i have not checked that the bin with musl already exists : chttps://github.com/biomejs/biome/releases/tag/cli%2Fv1.9.2
 
 So it there a clean way to force using this musl version of the bin ?
 
 Or some changes in the bundle are required ?
 
 Thank you again.

**Comment by srbetasign** [comment]
It seems that the method  BiomeJsBundle/src/BiomeJsBinary::getBinaryName() should be updated:
https://github.com/Kocal/BiomeJsBundle/blob/d675081c02e1640788bb7d9a4ffbf11b2d49effb/src/BiomeJsBinary.php#L152

**Comment by Kocal** [comment]
Hi @srbetasign, and thanks for your investigations :)

Would you mind sending a PR? I can help you if needed.

**Comment by srbetasign** [comment]
@Kocal, my friend @ralauge-aramis  who find the origin of this issue has created the PR : https://github.com/Kocal/BiomeJsBundle/pull/16
